#!/bin/bash

# Example usage script demonstrating how to use the SLURM job submission tools
# This is for demonstration purposes only - modify parameters for your actual runs

echo "=========================================="
echo "Example Usage of SLURM Job Scripts"
echo "=========================================="
echo ""
echo "This script demonstrates how to use the job submission tools."
echo "It will create example files but NOT submit any jobs."
echo ""

# Example configuration
EXAMPLE_INPUT="../oom_detectability/input.csv"
EXAMPLE_OUTPUT="../oom_detectability/test_output"
EXAMPLE_RUN_NAME="example_run"
NUM_JOBS=3
NUM_CORES=4

echo "Step 1: Split input file and create SLURM scripts"
echo "=================================================="
echo ""
echo "Command:"
echo "./split_and_submit.sh \\"
echo "    --input_file $EXAMPLE_INPUT \\"
echo "    --num_jobs $NUM_JOBS \\"
echo "    --run_name $EXAMPLE_RUN_NAME \\"
echo "    --output_dir $EXAMPLE_OUTPUT \\"
echo "    --num_cores $NUM_CORES \\"
echo "    --mag_plot \\"
echo "    --slurm_time 24:00:00 \\"
echo "    --slurm_mem 16G"
echo ""
read -p "Press Enter to see the next step..."
echo ""

echo "Step 2: Submit all jobs"
echo "======================"
echo ""
echo "Command:"
echo "./submit_all_jobs.sh $EXAMPLE_RUN_NAME"
echo ""
echo "This will submit all SLURM jobs for the run."
echo ""
read -p "Press Enter to see the next step..."
echo ""

echo "Step 3: Check job status"
echo "========================"
echo ""
echo "Command:"
echo "./check_job_status.sh $EXAMPLE_RUN_NAME"
echo ""
echo "This will show:"
echo "  - Jobs in the queue"
echo "  - Completion status"
echo "  - Recent errors"
echo ""
read -p "Press Enter to see the next step..."
echo ""

echo "Step 4: Monitor specific job logs"
echo "=================================="
echo ""
echo "Commands:"
echo "# View live log"
echo "tail -f ../slurm_scripts/${EXAMPLE_RUN_NAME}_job0.log"
echo ""
echo "# Check errors"
echo "cat ../slurm_scripts/${EXAMPLE_RUN_NAME}_job0.err"
echo ""
read -p "Press Enter to see the next step..."
echo ""

echo "Step 5: Cancel jobs if needed"
echo "=============================="
echo ""
echo "Command:"
echo "./cancel_all_jobs.sh $EXAMPLE_RUN_NAME"
echo ""
echo "This will cancel all running/pending jobs for the run."
echo ""
read -p "Press Enter to continue..."
echo ""

echo "=========================================="
echo "Additional Tips"
echo "=========================================="
echo ""
echo "1. Adjust SLURM parameters based on your cluster:"
echo "   --slurm_time: Maximum runtime (e.g., 48:00:00)"
echo "   --slurm_mem: Memory per job (e.g., 32G)"
echo "   --slurm_partition: Queue/partition name"
echo ""
echo "2. Edit SLURM scripts to load required modules:"
echo "   Edit: ../slurm_scripts/${EXAMPLE_RUN_NAME}_job*.slurm"
echo "   Add: module load python/3.9"
echo ""
echo "3. For very large runs, split into more jobs:"
echo "   --num_jobs 20  # For 20 parallel jobs"
echo ""
echo "4. Each job runs independently and writes to shared output"
echo "   Results: $EXAMPLE_OUTPUT/${EXAMPLE_RUN_NAME}_job*"
echo ""
echo "5. Check cluster status:"
echo "   squeue -u \$USER"
echo "   sinfo  # Show available partitions"
echo ""
echo "=========================================="
echo ""
echo "For more information, see README.md"
echo "=========================================="

